app/urls.py
# urls file just to handle all the routing for this app

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('loginp', views.loginp, name= 'loginp'),
    path('signup', views.signup, name='signup'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('signin', views.signin, name='signin'),
    path('signout', views.signout, name='signout'),
    path('fridge/', views.fridge, name ="fridge"),
    path('favorites/', views.favorites, name ="favorites"),
    path('myrecipes/', views.myrecipes, name ="myrecipes"),
    path('filtered_recipies/', views.filtered_recipies, name='filtered_recipies'),
    path('filtered_recipies/<str:cat>/', views.filtered_recipies, name='filtered_recipies'),
    path('filtered_recipies/<str:nome>/', views.filtered_recipies, name='filtered_recipies'),
    path('filtered_recipies/<str:cat>/<str:nome>/', views.filtered_recipies, name='filtered_recipies'),
    path('settings/', views.settings, name="settings"),
    path('adminPage/', views.adminPage, name="adminPage"),

    # views para a shoplist
    path('shoplist/', views.shoplist, name='shoplist'),
    path('add_ingredient_to_shoplist/', views.add_ingredient_to_shoplist, name='add_ingredient_to_shoplist'),
    path('delete_shoplist_item/<int:item_id>/', views.delete_shoplist_item, name='delete_shoplist_item'),


    path('recipepost/<int:id>', views.recipepost, name='recipepost'),
    path('delete_item/<int:item_id>/', views.delete_item, name='delete_item'),
    path('add_ingredient_to_fridge/', views.add_ingredient_to_fridge, name='add_ingredient_to_fridge'),
    path('delete_category/<int:cat_id>/', views.delete_category, name='delete_category'),
    path('create_category/', views.create_category, name='create_category'),
    path('delete_ingredient/<int:ing_id>/', views.delete_ingredient, name='delete_ingredient'),
    path('create_ingredient/', views.create_ingredient, name='create_ingredient'),

    path('newrecipe/',  views.createRecipe, name = "createRecipe"),
    path('updaterecipe/<str:pk>',  views.updateReceita, name = "updateReceita"),
    path('deleterecipe/<str:pk>',  views.deleteRecipe, name = "deleteRecipe"),
    path('add_to_favorites/<int:pk>/', views.add_to_favorites, name='add_to_favorites'),
    path('remove_from_favorites/<int:pk>/', views.remove_from_favorites, name='remove_from_favorites'),

    path('settings/', views.user_settings, name='user_settings'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webproj/urls.py
# Route directory urls file
from django.contrib import admin
from django.urls import include,path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from django.conf import settings
from django.conf.urls.static import static


from app import views

urlpatterns = [
    path('admin/',admin.site.urls),
    path('hello/', views.hello, name='hello'),
    path('index/', views.index, name='index'),
    path('',include('app.urls')),
    path('about/', views.about, name='about'),
    path('blog-post/', views.blogpost, name='blogPost'),
    path('elements/', views.elements, name='elements'),
    path('recipe-post/', views.recipepost, name='recipePost'),
    path('login/', views.login, name='login'),


]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
import os

from django.conf import settings
from django.conf.urls.static import static

# Create your models here.

# a classe que criar vai representar uma tabela da base de dados

class Categoria(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class CategoriaIngrediente(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
class CategoriaRefeicao(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
class Ingrediente(models.Model):
    nome = models.CharField(max_length=255)
    categoria = models.ForeignKey(CategoriaIngrediente, on_delete=models.SET_NULL, null=True)
    icon = models.CharField(max_length=255,null=True, blank=True)
    calorias = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.nome

class Receita(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True) # ambos os valores podem etar vazios
    tempoPreparacao = models.IntegerField(null=True, blank=True)
    tempoCozinhar = models.IntegerField(null=True, blank=True)
    quantidadePessoas = models.IntegerField(null=True, blank=True)
    nivel = models.IntegerField(null=True, blank=True)
    imagem = models.ImageField(upload_to='static/img',null=True, blank=True)  # 'upload_to' define o diretório de armazenamento
    ingredients = models.ManyToManyField(Ingrediente, through='ReceitaIngrediente')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def save(self, *args, **kwargs):
        if not self.imagem:  # Adicionando verificação para evitar chamadas desnecessárias
            super().save(*args, **kwargs)
            return

        filename = f'{slugify(self.name)}.jpg'  

        filepath = os.path.join(settings.MEDIA_ROOT, 'static/img', filename)
        with open(filepath, 'wb') as file:
            for chunk in self.imagem.chunks():
                file.write(chunk)

        self.imagem.name = os.path.join('static/img', filename)
        super().save(*args, **kwargs)



    def __str__(self):
        return self.name
    
# Modelo para Receitas_Receita_Ingrediente (tabela de associação)
class ReceitaIngrediente(models.Model):
    receita = models.ForeignKey(Receita, on_delete=models.CASCADE)
    ingrediente = models.ForeignKey(Ingrediente, on_delete=models.CASCADE)
    quantidade = models.FloatField(default=1.0)

    def __str__(self):
        return f"{self.ingrediente.nome} em {self.receita.name}"
    
class Avaliacao(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    receita = models.ForeignKey(Receita, on_delete=models.CASCADE) # quando o pai é eliminado, os filhos tb são
    descricao = models.TextField()
    clasificacao = models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])
    data = models.DateField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.descricao[0:50]
    

class Frigorifico(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingrediente, on_delete=models.CASCADE)
    data = models.DateField()
    checklist = models.BooleanField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.ingredient.nome} no frigorífico de {self.user.username}"


class Favoritos(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    receita = models.ForeignKey(Receita, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.receita.name} nos favoritos de {self.user.username}"


class ListaCompras(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingrediente, on_delete=models.CASCADE)
    data = models.DateField()
    checklist = models.BooleanField()

    def __str__(self):
        return f"{self.ingredient.nome} na lista de compras de {self.user.username}"

# Create your models here.
class Events(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255,null=True,blank=True)
    start = models.DateTimeField(null=True,blank=True)
    end = models.DateTimeField(null=True,blank=True)    

app/templates/about.html
{% extends 'main.html' %}

{% load static %}
{% block content %}

    <!-- ##### About Us Area Start ##### -->
    <section class="about-us-area">
        <div class="breadcumb-area bg-img bg-overlay" style="background-image: url({% static 'img/bg-img/breadcumb1.jpg' %});">
            <div class="container h-100">
                <div class="row h-100 align-items-center">
                    <div class="col-12">
                        <div class="breadcumb-text text-center">
                            <h2>About us</h2>
                            <p>This project was developed within the scope of the TPW course for Professor Hélder Zagalo</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container" style="margin-top: 50px">
            <div class="row">

                <!-- Team Members -->
                <div class="col-12">
                    <div class="single-about-content mb-100">
                        <h3>Team Members</h3>
                        <hr>
                        <div class="row">
                            <!-- Member 1 -->
                            <div class="col-md-4">
                                <div class="single-member" style="width: 75%; text-align: center">
                                    <img src="{% static 'img/about/mariana.png' %}" alt="Team Member 1">
                                    <h5 class="about-names">Mariana Perna</h5>
                                    <p>106087</p>
                                </div>
                            </div>
                            <!-- Member 2 -->
                            <div class="col-md-4">
                                <div class="single-member" style="width: 75%; text-align: center">
                                    <img src="{% static 'img/about/rafaela.png' %}" alt="Team Member 2">
                                    <h5 class="about-names">Rafaela Dias</h5>
                                    <p>108782</p>
                                </div>
                            </div>
                            <!-- Member 3 -->
                            <div class="col-md-4">
                                <div class="single-member" style="width: 75%; text-align: center">
                                    <img src="{% static 'img/about/vania.png' %}" alt="Team Member 3">
                                    <h5 class="about-names">Vânia Morais</h5>
                                    <p>102383</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Project Description -->
                <div class="col-12">
                    <div class="single-about-content mb-100">
                        <h3>Project Overview</h3>
                        <hr>
                        <p>Our website is a platform that allows users to explore, share, and discover a wide variety of delicious recipes. From main dishes to incredible desserts, our goal is to inspire culinary creativity and make cooking an enjoyable experience.</p>
                    </div>
                </div>

                <!-- Contact Information -->
                <div class="col-12">
                    <div class="contact-information mb-100">
                        <h3>Contact Us</h3>
                        <hr>
                        <p>Feel free to reach out to us for any inquiries or feedback.</p>
                        <div id="map" style="height: 500px;"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### About Us Area End ##### -->

    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
    <script>
        // Coordenadas da Universidade de Aveiro
        var universityLatLng = [40.63328706005596, -8.659450387263156];

        // Configuração do mapa
        var map = L.map('map').setView(universityLatLng, 17);

        // Adiciona um marcador
        L.marker(universityLatLng).addTo(map)
            .bindPopup('Universidade de Aveiro');

        // Adiciona um tile do OpenStreetMap
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '© OpenStreetMap contributors'
        }).addTo(map);
    </script>

{% endblock content %}

app/templates/adminPage.html
{% extends 'main.html' %}

{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <h3 class="mt-5">Categories</h3>
            <hr>
            <div class="row">
                <div class="col-12">
                    <ul class="list-group">
                        {% for cat in categorias %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="#">{{ cat.name }}</a>
                            <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#confirmDelete{{cat.id}}">Delete</button>
                        </li>
                        <!-- Modal de confirmação de exclusão -->
                        <div class="modal fade" id="confirmDelete{{cat.id}}" tabindex="-1" role="dialog" aria-labelledby="deleteRecipeModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteRecipeModalLabel">Confirm Deletion</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Are you sure you want to delete "{{cat.name}}"?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
                                        <form method="POST" action="{% url 'delete_category' cat.id %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="recipe_id" value="{{ cat.id }}">
                                            <input type="submit" class="btn btn-danger" value="Confirm">
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% empty %}
                        <li class="list-group-item">Nenhuma categoria disponível.</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="row" style="margin-top: 20px">
                <div class="col-12">
                    <form method="post" action="{% url 'create_category' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" id="categoryName" name="categoryName" class="form-control" required>
                        </div>
                        <button type="submit" class="btn delicious-btn" data-animation="fadeInUp" data-delay="1000ms">Add Category</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-6">
            <h3 class="mt-5">Ingredients</h3>
            <hr>
            <div class="row">
                <div class="col-12">
                    <ul class="list-group">
                        {% for ing in ingredientes %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="#">{{ ing.nome }}</a>
                            <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#delete{{ing.id}}">Delete</button>
                        </li>
                        <div class="modal fade" id="delete{{ing.id}}" tabindex="-1" role="dialog" aria-labelledby="deleteIngredientModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteIngredientModalLabel">Confirm Deletion</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Are you sure you want to delete "{{ing.nome}}"?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
                                        <form method="POST" action="{% url 'delete_ingredient' ing.id %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="ing_id" value="{{ ing.id }}">
                                            <button type="submit" class="btn btn-danger">Confirm</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% empty %}
                        <li class="list-group-item">Nenhum ingrediente disponível.</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="row" style="margin-top: 20px">
                <div class="col-12">
                    <form method="post" action="{% url 'create_ingredient' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" id="ingredientName" name="ingredientName" class="form-control" required>
                        </div>
                        <button type="submit" class="btn delicious-btn" data-animation="fadeInUp" data-delay="1000ms">Add Ingredient</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/delete.html
{% extends 'main.html' %}

{% block content %}

<form method="POST" action="">
    {% csrf_token %}
    {{form.as_p}}
    <p> Are you sure you want to delete "{{obj.name}}"? </p>
    
    <a href="{{ request.META.HTTP_REFERER }}"> Go Back </a>
    <input type="hidden" name="recipe_id" value="{{ obj.id }}">
    <input type="submit" value="Confirm"/>

</form>


{% endblock content %}

app/templates/newrecipe.html
{% extends 'main.html' %}

{% block content %}

<h1 style="margin-left:20px"> My new Recipe </h1>

<div style="margin-left:20px">
    <div>
        
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn" type="submit" value="Submit" />
        </form>
        
    </div>
</div>

{% endblock content %}

app/templates/planner.html
{% extends "base.html" %}
   
{% block content %}
<div class="col-md-12">    
    <div id='calendar'></div> 
</div> 
{% endblock content %} 

app/templates/recipe-post.html
{% extends 'main.html' %}

{% load static %}

{% block content %}


    <div class="receipe-post-area">

        

        <!-- Receipe Slider -->
        <div class="container">
            <div class="row">
                <div class="col-12">
                    {% comment %} <div class="receipe-slider owl-carousel">
                        {%if receita.imagem.url %}
                            <img src="{{ receita.imagem.url }}" alt="" style="object-fit: cover; height:400px">
                            <img src="{{ receita.imagem.url }}" alt="" style="object-fit: cover; height:400px">
                            <img src="{{ receita.imagem.url }}" alt="" style="object-fit: cover; height:400px">
                        {%else%}
                            <img src="{% static "img/blog-img/1.jpg" %}%}" alt="" style="object-fit: cover; height:400px">
                            <img src="{% static "img/blog-img/1.jpg" %}%}" alt="" style="object-fit: cover; height:400px">
                            <img src="{% static "img/blog-img/1.jpg" %}%}" alt="" style="object-fit: cover; height:400px">
                        {%endif%}
                    </div> {% endcomment %}
                    <div class="receipe-slider owl-carousel owl-not-carousel" style="display: block;">
                        {% if receita.imagem %}
                            <img src="{{ receita.imagem.url }}" alt="" style="object-fit: cover; height: 400px; width: 100%">
                        {% else %}
                            <img src="{% static "img/blog-img/1.jpg" %}" alt="" style="object-fit: cover; height: 400px; width: 100%">
                        {% endif %}
                    </div>

                    
                </div>
            </div>
        </div>

        <!-- Receipe Content Area -->
        <div class="receipe-content-area">
            <div class="container">

                <div class="row">
                    <div class="col-12 col-md-8">
                        <div class="receipe-headline my-5">
                            <h2>{{receita.name}}</h2>
                            <div class="receipe-duration">
                                <h6>Prep: {{receita.tempoPreparacao}} mins</h6>
                                <h6>Cook: {{receita.tempoCozinhar}} mins</h6>
                                <h6>Yields: {{receita.quantidadePessoas}} Servings</h6>
                                <h6>Level: {{receita.nivel}}</h6>
                            </div>
                        </div>
                    </div>

                    <div class="col-12 col-md-4">
                        <div class="receipe-ratings text-right my-5">
                            <div class="ratings">
                                {% for i in "xxxxx" %}
                                    {% if forloop.counter <= media_avaliacoes %}
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                    {% else %}
                                        <i class="fa fa-star-o" aria-hidden="true"></i>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-lg-8">
                        <!-- Single Preparation Step -->
                        <div class="single-preparation-step d-flex">
                            <h4>01.</h4>
                            <p>{{receita.description}}</p>
                        </div>
                    </div>

                    <!-- Ingredients -->
                    <div class="col-12 col-lg-4">
                        <div class="ingredients">
                            <h4>Ingredients</h4>
                            {% for ingredientes in receita.receitaingrediente_set.all %}
                                <!-- Custom Checkbox -->
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="customCheck{{ forloop.counter }}" {% if ingredientes.ingrediente.id in user_fridge %}checked{% endif %}>
                                    <label class="custom-control-label" for="customCheck{{ forloop.counter }}">
                                        {{ ingredientes.ingrediente.nome }} ({{ ingredientes.quantidade }})
                                    </label>
                                </div>
                            {% endfor %}

                        </div>
                    </div>
                </div>

                {% if user.is_authenticated %}
                <div style="padding-top: 30px; padding-bottom: 30px">
                    <button id="add-to-favorites" class="btn delicious-btn mt-30">Add to Favorites</button>
                    {% if user.is_authenticated and user == receita.user or  user.is_superuser %}
                    <a class="btn delicious-btn mt-30"  href="{% url 'updateReceita' receita.id %}">Update Recipe</a>
                    <!-- Link para abrir o modal -->
                    <a class="btn delicious-btn mt-30" data-toggle="modal" data-target="#deleteRecipeModal">Delete Recipe</a>

                    <!-- Modal de confirmação de exclusão -->
                    <div class="modal fade" id="deleteRecipeModal" tabindex="-1" role="dialog" aria-labelledby="deleteRecipeModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="deleteRecipeModalLabel">Confirm Deletion</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p>Are you sure you want to delete "{{receita.name}}"?</p>
                                </div>
                                <div class="modal-footer">
                                    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
                                    <form method="POST" action="{% url 'deleteRecipe' pk=receita.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="recipe_id" value="{{ receita.id }}">
                                        <input type="submit" class="btn btn-danger" value="Confirm">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% endif %}
                </div>

                {% endif %}

                <div class="comments-box" style="padding-top:50px; padding-bottom:50px;">
                    <h3>Comments</h3>
                    <ul class="comment-list">
                        {% for comment in avaliacoes %}
                            <li class="comment-item" style="padding-bottom:10px">
                                <div class="comment-author">
                                    <img src="{% static 'img/avatar.png' %}" alt="User Avatar" width="100" height="100">
                                    <span>{{ comment.user.username }}</span>
                                </div>
                                <div class="comment-content">
                                    <p>{{ comment.descricao }}</p>
                                    <div class="comment-rating">
                                        {% for i in "xxxxx" %}
                                            {% if forloop.counter <= comment.clasificacao %}
                                                <i class="fa fa-star" aria-hidden="true"></i>
                                            {% else %}
                                                <i class="fa fa-star-o" aria-hidden="true"></i>
                                            {% endif %}
                                        {% endfor %}
                                    </div>                                                                    
                                    <small>{{ comment.data }}</small>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                

                {% if user.is_authenticated %}
                    <div class="row">
                        <div class="col-12">
                            <div class="section-heading text-left">
                                <h3>Leave a comment</h3>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12">
                            <div class="contact-form-area">
                                <form method="post">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <div class="col-12">
                                        <button class="btn delicious-btn mt-30" type="submit">Post Comments</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endif %}
                
            </div>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var receitaId = '{{ receita.id }}';
            var addToFavoritesButton = document.getElementById('add-to-favorites');
    
            if (addToFavoritesButton) {
                addToFavoritesButton.addEventListener('click', function () {
                    var url = '/add_to_favorites/' + receitaId + '/';
    
                    fetch(url)
                        .then(response => response.json())
                        .then(data => {
                            if (data.success) {
                                alert(data.message);
                            } else {
                                alert(data.message);
                            }
                        })
                        .catch(error => console.error('Error:', error));
                });
            }
        });
    </script>
    
    

    {% endblock content %} 